spring.application.name=employee-management-system

# Railway MySQL Configuration
spring.datasource.url=${MYSQL_URL}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Railway Dynamic Port
server.port=${PORT:8080}

# JWT
jwt.secret=yourSecretKeyForJWTAuthentication123456789
jwt.expiration=86400000